config_version = 14

[audio]
enable_overdrive = true
sound_volume = 0.29999999329447746

[bar.default]
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "volume",
    "network",
    "bluetooth",
    "brightness",
    "battery",
    "control-center",
    "session"
]
margin_ends = 0
start = [ "wallpaper", "workspaces" ]
thickness = 30
widget_spacing = 10

    [bar.default.monitor.DP-3]
    enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "lockscreen-login-box@DP-2", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 512.0
    cy = 586.0
    output = "DP-3"
    placement_height = 768.0
    placement_width = 1024.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[shell]
font_family = "Iosevka Nerd Font"

[theme]
community_palette = "Catppuccin Mocha Blue"
pure_black_dark = true
source = "community"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/tom/Pictures/Wallpapers/colorful"

    [wallpaper.default]
    path = "/home/tom/Pictures/Wallpapers/colorful/wallhaven-rqod21_1920x1080.png"

    [wallpaper.last]
    path = "/home/tom/Pictures/Wallpapers/colorful/wallhaven-rqod21_1920x1080.png"

[widget.clock]
capsule = true
capsule_fill = "on_primary"
capsule_radius = 21
font_weight = 700
format = "{:%d/%m/%y %H:%M:%S}"

[widget.media]
max_length = 280
show_progress = true