#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Tomkoid"
email = "tomkoid@tomkoid.cz"

[ui]
default-command = "log"
editor = "nvim"
pager = "delta"
diff-formatter = ":git"

[signing]
behavior = "own"
backend = "gpg"
## You can set `key` to anything accepted by `gpg -u`
## If not set then defaults to the key associated with `user.email`
key = "D4403E79602EE85B"
# key = "signing@example.com"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
tup = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"]
