### Format for time is HH:MM:SS
sunrise_time = "07:00"
sunset_time = "12:00"

# Night time screen temperature
sunset_temperature = 2500

# Interval at which to update the screen temperature and respond to events (in milliseconds)
tick_interval = 250

# Restart on wake-up
restart_on_wakeup = true
