#!/bin/sh

CONFIG_PATH="${HOME}/.config/bspwm"

WINDOW_GAP=10
BORDER_WIDTH=2
TOP_PADDING=25

# Load monitor config
$HOME/.screenlayout/setup.sh

# Load gap script
$CONFIG_PATH/scripts/gap.sh &

# Start Polybar
polybar main &
polybar vga &

# Lock the screen after timeout
xss-lock --transfer-sleep-lock -- i3lock -c 000000 --nofork &

# Restore wallpaper
nitrogen --restore &

# Start picom
picom &

# Start mouse sensitivity script
bash ~/.config/bspwm/scripts/sensitivity.sh &

# Start notification daemon
dunst &

# Set cursor theme
xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor VGA-1 -d 6 7 8 9 10
# bspc monitor LVDS-1 -d 1 2 3 4 5

start_from=1
monitors_connected=$(bspc query -M | wc -l)
real_monitors_connected=$(xrandr | grep " connected " | awk '{ print $1 }' | wc -l)
if [[ "$real_monitors_connected" -lt 2 ]]
then
  for monitor in $(bspc query -M); do
    bspc monitor $monitor -r
  done
  bspc monitor $(bspc query -M -d) -d 1 2 3 4 5 6 7 8 9 0
else
  per_monitor=$(( 10 / monitors_connected ))
  for monitor in $(xrandr | grep " connected " | awk '{ print $1 }'); do
    bspc monitor $monitor -d $(seq $start_from $(( start_from + per_monitor - 1)))
    bspc config -m $monitor top_padding $TOP_PADDING
    start_from=$(( start_from + per_monitor ))
  done
fi

# Window behaviour
bspc config border_width        $BORDER_WIDTH
bspc config window_gap          $WINDOW_GAP
# bspc config top_padding         $TOP_PADDING

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config automatic_scheme     master
# bsp-layout set tall

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Element desktop='4' follow=off focus=off
bspc rule -a conky desktop='6' state=floating border=off
